### ISSUE TITLE
Device won't be charged unless the system booted

### ISSUE THREAD

**Issue by FTS427** [Bakoubak/amar_row_lte-A11-releases#11]
**Describe the bug**
I can't charge my tablet when it was powered off. When I plug the charging cable into it while it was powered off, it just show a warning about my BL lock from mtk and it won't show my device charging status. And if I leave it like this for a while, it will get hot.

**To Reproduce**
1. Poweroff the device
2. Plug the charging cable
3. See error

**Expected behavior**
I hope I can charge the device while it is powered off and I can see its charging status

**Screenshots**

![Image](https://github.com/user-attachments/assets/978bbb02-b49b-459b-8345-7cdb091ffe31)

> The warning says:
>
> *Orange State*
> 
> *Your device has been unlocked and can't be trusted*
> *Your device will boot in 5 seconds*

**LineageOS version**
[LineageOS 19-20250710-UNOFFICIAL-amar_row_lte](https://github.com/Bakoubak/amar_row_lte-A11-releases/releases/download/25.07-alpha-2-hf2/LineageOS-19.1_amar-row-lte-11_ALPHA2-HF2.zip)
Stock firmware version: TB_X306X_S230973_240402_BMP

**Logs**

[dmesg.txt](https://github.com/user-attachments/files/21820481/dmesg.txt)
[logcat.mt8768.txt](https://github.com/user-attachments/files/21820482/logcat.mt8768.txt)
[ramoops.txt](https://github.com/user-attachments/files/21820483/ramoops.txt)

**Additional context**
None

**Comment by Bakoubak** [comment]
It is actually charging but the POC screen is not configured, it is fixed in the next release but i can't build until i fix the build machine

**Comment by FTS427** [comment]
this bug still appeared in [LineageOS-20.0-ALPHA-30-08-2025](https://github.com/Bakoubak/amar_row_lte-A11-releases/releases/download/25.08-alpha-3/LineageOS-20.0-ALPHA-30-08-2025.zip)
